In [95]:
import numpy as np
import pandas as pd

In [96]:
df = pd.read_csv("lacResults2016.csv")
df.drop(df.columns[0], axis=1, inplace=True)
df.head()

,Constituency,District,UDF candidate,Party,Votes,LDF candidate,Party.1,Votes.1,NDA candidate,Party.2,Votes.2,Winner,Margin,Winning Alliance
0,Manjeshwar,Kasaragod,P.B. Abdul Razak,IUML,56870,C.H. Kunjambu,CPI(M),42565,K. Surendran (politician),BJP,56781,P.B. Abdul Razak,89,UDF
1,Kasargod,Kasaragod,N.A. Nellikkunnu,IUML,64727,A.A. Ameen,INL,21615,K. Ravisha Tantri,BJP,56120,N.A. Nellikkunnu,8607,UDF
2,Udma,Kasaragod,K. Sudhakaran,INC,66847,K. Kunhiraman,CPI(M),70679,Sreekanth,BJP,21231,K Kunhiraman,3832,LDF
3,Kanhangad,Kasaragod,Dhanya Suresh,INC,54547,E. Chandrasekharan,CPI,80558,M.P. Raghavan,BDJS,21104,E Chandrasekharan,26011,LDF
4,Thrikkaripur,Kasaragod,K.P. Kunhikannan,INC,62327,M. Rajagopal,CPI(M),79286,M. Bhaskaran,BJP,10767,M Rajagopal,16959,LDF

In [97]:
newcols1 = ['Constituency', 'District', 'Candidate', 'Party', 'Votes']
part1 = df.iloc[:,0:5]
part1.columns = newcols1
newcols2 = newcols1[2:5]
part2 = df.iloc[:,5:8]
part2.columns = newcols2
part3 = df.iloc[:,8:11]
part3.columns = newcols2

comp = pd.concat([part1, part2, part3], axis=0)
comp.reset_index(inplace=True)
comp.drop('index', axis=1, inplace=True)
comp['Alliance'] = pd.DataFrame(['UDF']*140 + ['LDF']*140 + ['NDA']*140)
comp['Constituency'] = pd.concat([comp.iloc[0:140,1]] * 3).tolist()
comp['District'] = pd.concat([comp.iloc[0:140,2]] * 3).tolist()

In [98]:
const1 = pd.read_csv('../electionPdf/ge2016/csvs/001.csv', skiprows=[0,1])
const1.drop([170], axis=0, inplace=True)

In [100]:
# const1.loc[:,["{:d}".format(x) for x in range(1,22)]] = const1.loc[:,["{:d}".format(x) for x in range(1,22)]].apply(pd.to_numeric, errors='coerce')
const1[const1.columns[1:22]] = const1[const1.columns[1:22]].apply(pd.to_numeric, errors='coerce')
const1.head()
const1.columns

Index(['Serial No of Polling Station', '1', '2', '3', '4', '5', '6', '7', '8',
       '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
       '21', 'Total # of Valid Votes', '# of Rejected', 'Total',
       '# of Tend Vote'],
      dtype='object')

In [101]:
c1 = const1.transpose()
c1.columns = c1.iloc[0,:]
c1.drop(c1.index[0], axis=0, inplace=True)
c1.head()

Serial No of Polling Station,001,002,003,004,005,006,007,008,009,010,...,161,162,163,164,165,166,167,Total No of Votes recorded at Polling,No.of Votes recorded on postal ballot papers(To be filled in the case of election from assembly constituency),Total Votes Polled
1,383,303,356,403,250,412,697,102,674,383,...,176,162,148,42,136,75,50,56828,42,56870
2,233,170,124,103,102,248,162,159,140,237,...,125,223,259,372,161,283,300,42497,68,42565
3,3,2,1,4,0,1,1,0,1,4,...,5,4,2,5,10,1,1,365,0,365
4,367,412,402,447,408,533,140,750,194,418,...,571,483,306,695,438,324,347,56591,190,56781
5,6,0,4,1,2,8,21,4,22,31,...,7,1,0,4,2,1,1,759,0,759

In [105]:
c1.columns.name=None
c1.columns

Index(['001 ', '002 ', '003 ', '004 ', '005 ', '006 ', '007 ', '008 ', '009 ',
       '010 ',
       ...
       '161 ', '162 ', '163 ', '164 ', '165 ', '166 ', '167 ',
       'Total No of Votes recorded at Polling',
       'No.of Votes recorded on postal ballot papers(To be filled in the case of election from assembly constituency)',
       'Total Votes Polled'],
      dtype='object', length=170)

In [106]:
c1=c1.apply(pd.to_numeric, errors = 'coerce')
c1.head()

,001,002,003,004,005,006,007,008,009,010,...,161,162,163,164,165,166,167,Total No of Votes recorded at Polling,No.of Votes recorded on postal ballot papers(To be filled in the case of election from assembly constituency),Total Votes Polled
1,383.0,303.0,356.0,403.0,250.0,412.0,697.0,102.0,674.0,383.0,...,176.0,162.0,148.0,42.0,136.0,75.0,50.0,56828.0,42.0,56870.0
2,233.0,170.0,124.0,103.0,102.0,248.0,162.0,159.0,140.0,237.0,...,125.0,223.0,259.0,372.0,161.0,283.0,300.0,42497.0,68.0,42565.0
3,3.0,2.0,1.0,4.0,0.0,1.0,1.0,0.0,1.0,4.0,...,5.0,4.0,2.0,5.0,10.0,1.0,1.0,365.0,0.0,365.0
4,367.0,412.0,402.0,447.0,408.0,533.0,140.0,750.0,194.0,418.0,...,571.0,483.0,306.0,695.0,438.0,324.0,347.0,56591.0,190.0,56781.0
5,6.0,0.0,4.0,1.0,2.0,8.0,21.0,4.0,22.0,31.0,...,7.0,1.0,0.0,4.0,2.0,1.0,1.0,759.0,0.0,759.0

In [107]:
comp['Votes'] = comp['Votes'].apply(pd.to_numeric, errors = 'coerce')
comp.head()

          Candidate  Constituency   District Party    Votes Alliance
0  P.B. Abdul Razak    Manjeshwar  Kasaragod  IUML  56870.0      UDF
1  N.A. Nellikkunnu      Kasargod  Kasaragod  IUML  64727.0      UDF
2     K. Sudhakaran          Udma  Kasaragod   INC  66847.0      UDF
3     Dhanya Suresh     Kanhangad  Kasaragod   INC  54547.0      UDF
4  K.P. Kunhikannan  Thrikkaripur  Kasaragod   INC  62327.0      UDF

In [108]:
pd.merge(c1, comp, left_on="Total Votes Polled", right_on='Votes', how='inner', suffixes=('_x', '')).dropna(axis=1)

,001,002,003,004,005,006,007,008,009,010,...,167,Total No of Votes recorded at Polling,No.of Votes recorded on postal ballot papers(To be filled in the case of election from assembly constituency),Total Votes Polled,Candidate,Constituency,District,Party,Votes,Alliance
0,383.0,303.0,356.0,403.0,250.0,412.0,697.0,102.0,674.0,383.0,...,50.0,56828.0,42.0,56870.0,P.B. Abdul Razak,Manjeshwar,Kasaragod,IUML,56870.0,UDF
1,233.0,170.0,124.0,103.0,102.0,248.0,162.0,159.0,140.0,237.0,...,300.0,42497.0,68.0,42565.0,C.H. Kunjambu,Manjeshwar,Kasaragod,CPI(M),42565.0,LDF
2,367.0,412.0,402.0,447.0,408.0,533.0,140.0,750.0,194.0,418.0,...,347.0,56591.0,190.0,56781.0,K. Surendran (politician),Manjeshwar,Kasaragod,BJP,56781.0,NDA